<a href="https://colab.research.google.com/github/murillodomingos/Criptografia/blob/main/criptografia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Construção de um algoritimo de criptografia a partir da "Cifra de Hill"


**Integrantes**:

  Bruno Neves Boa Sorte -  NºUSP: 14562528

  Caio Uramoto Evangelista - NºUSP: 14777351

  Murillo Domingos de Almeida - NºUSP: 14804083

 **Prof**: Maria Luisa Bambozzi



#Funcionamento do algoritmo

*   Tranformação da mensagem para números

*   Agrupamento dos números

*   Multiplicação por uma matriz 3 x 3, a qual será a chave

*   verificação da inversibilidade da matriz chave

* funções de codificação e decodificação



#  objetivo
  multiplicar a mensagem encriptada pela inversa da
  
  chave e obter a mensagem original


In [ ]:
import numpy as np # Biblioteca utilizada para facilitar operações matriciais
import random # Utilizado para gerar chaves aleatorias


In [ ]:
# Verifica se é inversível a matriz chave, caso a função retorne erro não é inversível
def verifica_inversibilidade(chave):
  matriz = chave

  try:
    inv_matriz = np.linalg.inv(matriz) #  Funcao que calcula a matriz inversa, em que, ao mutiplica-la pela original resulta na matriz identidade.
    return True
  except np.linalg.LinAlgError:
    return False


In [ ]:
# Tranforma a mensagem em um vetor de números
def transformacao_para_numeros(mensagem):
  msg_numerica = []

  for e in mensagem:
    msg_numerica.append((ord(e))) # transforma de caracter para ascii

  return msg_numerica


In [ ]:
# Transforma o vetor de números em uma matriz n x 3, agrupando-os
def agrupa_numeros(mensagem):
  lista = transformacao_para_numeros(mensagem)
  if(len(lista) % 3 == 0):
    linhas = len(lista) // 3
  else:
    linhas = (len(lista) // 3) + 1
    zeros = linhas * 3 - len(lista)
    for z in range(zeros):
      lista.append(0)

  k = 0
  matriz = [[0] * 3 for l in range(linhas)]

  for i in range(linhas):
    for j in range(3):
      matriz[i][j] = lista[k]
      k += 1
  return(matriz)


In [ ]:
# Cria uma chave aleatória
def cria_chave():
  chave = np.empty((3, 3))
  for i in range(3):
    for j in range(3):
      chave[i][j] = random.randint(0, 254)
  if np.linalg.det(chave) % 255 == 0: # Função utilizada para calcular a determinante, há varios processos para obte-la mas na funcao é utilizada a eliminacao de Gauss
    cria_chave()

  return chave


In [ ]:
# Codifica a mensagem multiplicando a matriz obtida com a chave
def codifica_matriz(mensagem, chave):
  matriz = agrupa_numeros(mensagem)
  return np.dot(matriz, chave) # Funcao que multiplica duas matrizes


In [ ]:
# Decodifica a partir da mensagem encriptada e da chave
def decodifica_matriz(codigo, chave):
  inv_matriz = np.linalg.inv(chave)
  matriz_n = np.dot(codigo, inv_matriz)

  linhas = len(matriz_n)
  f_original = []

  matriz = np.round(matriz_n).astype(int)

  for i in range(linhas):
    for j in range(3):
      if matriz[i][j] != 0:
        elemento = chr(matriz[i][j]) # Transforma de ascii para caracter
        f_original.append(elemento)

  return f_original


In [ ]:
#Bloco principal
print("-------------Criptografia-------------")
print("Codificar com chave aleatória [aleatoria]")
print("Codificar com chave do usúario [usuario]")
print("Decodificar [decodificar]")

operacao = str(input("Qual opção você deseja?: "))

if (operacao == "aleatoria"):
  mensagem = str(input("Digite sua mensagem: "))
  chave = cria_chave()
  print("----------------------Esta é a chave---------------------- \n", chave)

  print("----------------------Matriz codificada---------------------- \n")
  resultado = codifica_matriz(mensagem, chave)
  print(resultado)
  print("----------------------Matriz decodificada---------------------- \n", ''.join(decodifica_matriz(resultado, chave)))

elif (operacao == "usuario"):
  mensagem = str(input("Digite sua mensagem: "))
  chave = [[0] * 3 for l in range(3)]

  print("----------------------Digite sua chave inversível-----------------")
  for i in range(3):
    for j in range(3):
        chave[i][j] = int(input(f'Digite o valor para a posição ({i+1}, {j+1}): '))

  if not verifica_inversibilidade(chave):
    print("Essa matriz não é inversível")
  else:
    print("----------------------Matriz codificada---------------------- \n")
    resultado = codifica_matriz(mensagem, chave)
    print(resultado)
    print("----------------------Matriz decodificada---------------------- \n", ''.join(decodifica_matriz(resultado, chave)))

elif (operacao == "decodificar"):
  lin = int(input("Quantas linhas tem seu código criptografado? "))
  codigo = [[0] * 3 for l in range(lin)]
  chave = [[0] * 3 for l in range(3)]

  print("Digite o código criptografado\n")
  for i in range(lin):
    for j in range(3):
        codigo[i][j] = int(input(f'Digite o valor para a posição ({i+1}, {j+1}): '))

  print("Digite a sua chave\n")
  for i in range(3):
    for j in range(3):
        chave[i][j] = int(input(f'Digite o valor para a posição ({i+1}, {j+1}): '))

  if not verifica_inversibilidade(chave):
    print("Essa matriz não é inversível")
  else:
    print(decodifica_matriz(codigo, chave))

else:
  print("Código inválido")


-------------Criptografia-------------
Codificar com chave aleatória [aleatoria]
Codificar com chave do usúario [usuario]
Decodificar [decodificar]
Qual opção você deseja?: aleatoria
Digite sua mensagem: dfggfgiufsicjiahsajsd
----------------------Esta é a chave---------------------- 
 [[126. 233.  46.]
 [ 29. 230.  34.]
 [ 93. 254. 247.]]
----------------------Matriz codificada---------------------- 

[[25137. 72922. 33509.]
 [25515. 73621. 33647.]
 [26109. 77283. 34002.]
 [26742. 76091. 33313.]
 [25422. 73486. 32405.]
 [25460. 75320. 32653.]
 [25991. 76548. 33486.]]
----------------------Matriz decodificada---------------------- 
 dfggfgiufsicjiahsajsd
